#!/usr/bin/env bash

set -Eeuo pipefail

# Interactively generates .env for this checkout from .env.example, instead
# of hand-copying and editing it, then carries on through the rest of
# environment setup (create the database, apply the schema, install cron
# jobs, start the app) so a person can go from a fresh checkout to a
# running app with just this one command in one terminal. Run once per
# checkout, after scripts/setup_server.sh has created the shared
# PostgreSQL container and the venv has been created (see scripts/README.md).
#
# Prompts for the PostgreSQL password chosen in scripts/setup_server.sh — it
# is never stored, guessed, or hardcoded by this script. SECRET_KEY is
# generated automatically (it's a random token, not something to remember).

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"

if [[ ! -t 0 || ! -t 1 ]]; then
    echo "ERROR: run this yourself in a terminal — it prompts for a password," >&2
    echo "which needs a person typing directly into a real tty." >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE already exists. Edit it by hand instead of overwriting it."
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found (needed to generate SECRET_KEY)."
    exit 1
fi

echo "=== Generating .env for this checkout ==="
echo "Checkout directory: $PROJECT_DIR"
echo

PORT=""
while [[ -z "$PORT" ]]; do
    read -r -p "Port (must not already be used by another checkout on this machine): " PORT
done

DEFAULT_DB_NAME="$(basename "$PROJECT_DIR" | tr '-' '_')"
read -r -p "Database name [$DEFAULT_DB_NAME]: " DB_NAME
DB_NAME="${DB_NAME:-$DEFAULT_DB_NAME}"

PG_PASSWORD=""
while [[ -z "$PG_PASSWORD" ]]; do
    read -r -s -p "PostgreSQL 'casaos' user password (set in scripts/setup_server.sh): " PG_PASSWORD
    echo
done

SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init_env.sh for the checkout at $PROJECT_DIR.
SECRET_KEY=$SECRET_KEY

# Use 0.0.0.0 when the application must be reachable from a mobile device on the LAN/Tailscale.
HOST=0.0.0.0
LOG_LEVEL=INFO

DATABASE_URL=postgresql://casaos:$PG_PASSWORD@localhost:5432/$DB_NAME
DB_NAME=$DB_NAME

PORT=$PORT
EOF

unset PG_PASSWORD

chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (permissions 600, not committed to git)."

echo
if docker exec postgresql psql -U casaos -lqt 2>/dev/null | cut -d'|' -f1 | grep -qw "$DB_NAME"; then
    echo "Database '$DB_NAME' already exists, skipping creation."
else
    echo "Creating database '$DB_NAME'..."
    docker exec postgresql createdb -U casaos "$DB_NAME"
fi

echo
"$PROJECT_DIR/scripts/init_database.sh"

echo
"$PROJECT_DIR/scripts/install_cron.sh"

echo
"$PROJECT_DIR/scripts/start_app.sh"

echo
echo "=== Environment setup complete ==="
echo "App running on http://localhost:$PORT (default login: admin/admin — change"
echo "the password after first login if this environment is reachable by anyone"
echo "other than you)."
