#!/usr/bin/env bash

set -Eeuo pipefail

# Interactively generates .env for this checkout from .env.example, instead
# of hand-copying and editing it. Run once per checkout, after
# scripts/setup_server.sh has created the shared PostgreSQL container.
#
# Prompts for the PostgreSQL password chosen in scripts/setup_server.sh — it
# is never stored, guessed, or hardcoded by this script. SECRET_KEY is
# generated automatically (it's a random token, not something to remember).

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"

if [[ ! -t 0 || ! -t 1 ]]; then
    echo "ERROR: run this yourself in a terminal — it prompts for a password," >&2
    echo "which needs a person typing directly into a real tty." >&2
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE already exists. Edit it by hand instead of overwriting it."
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found (needed to generate SECRET_KEY)."
    exit 1
fi

echo "=== Generating .env for this checkout ==="
echo "Checkout directory: $PROJECT_DIR"
echo

PORT=""
while [[ -z "$PORT" ]]; do
    read -r -p "Port (must not already be used by another checkout on this machine): " PORT
done

DEFAULT_DB_NAME="$(basename "$PROJECT_DIR" | tr '-' '_')"
read -r -p "Database name [$DEFAULT_DB_NAME]: " DB_NAME
DB_NAME="${DB_NAME:-$DEFAULT_DB_NAME}"

PG_PASSWORD=""
while [[ -z "$PG_PASSWORD" ]]; do
    read -r -s -p "PostgreSQL 'casaos' user password (set in scripts/setup_server.sh): " PG_PASSWORD
    echo
done

SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init_env.sh for the checkout at $PROJECT_DIR.
SECRET_KEY=$SECRET_KEY

# Use 0.0.0.0 when the application must be reachable from a mobile device on the LAN/Tailscale.
HOST=0.0.0.0
LOG_LEVEL=INFO

DATABASE_URL=postgresql://casaos:$PG_PASSWORD@localhost:5432/$DB_NAME
DB_NAME=$DB_NAME

PORT=$PORT
EOF

unset PG_PASSWORD

chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (permissions 600, not committed to git)."
echo
echo "Next:"
echo "  docker exec postgresql createdb -U casaos $DB_NAME"
echo "  ./scripts/init_database.sh"
