#!/usr/bin/env bash

set -Eeuo pipefail

# Interactively generates .env for this checkout from .env.example, instead
# of hand-copying and editing it. Run once per checkout (alpha/beta/production),
# after scripts/setup_server.sh has created the shared PostgreSQL container.
#
# Prompts for the PostgreSQL password chosen in scripts/setup_server.sh — it
# is never stored, guessed, or hardcoded by this script. SECRET_KEY is
# generated automatically (it's a random token, not something to remember).

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$PROJECT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "ERROR: $ENV_FILE already exists. Edit it by hand instead of overwriting it."
    exit 1
fi

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 not found (needed to generate SECRET_KEY)."
    exit 1
fi

echo "=== Generating .env for this checkout ==="
echo "Checkout directory: $PROJECT_DIR"
echo

ENV_NAME=""
while [[ -z "$ENV_NAME" ]]; do
    read -r -p "Environment name (alpha/beta/production): " ENV_NAME
done

case "$ENV_NAME" in
    alpha) DEFAULT_PORT=5002 ;;
    beta) DEFAULT_PORT=5001 ;;
    production) DEFAULT_PORT=5000 ;;
    *)
        echo "Unrecognized environment name '$ENV_NAME' — no default port available."
        DEFAULT_PORT=""
        ;;
esac

if [[ -n "$DEFAULT_PORT" ]]; then
    read -r -p "Port [$DEFAULT_PORT]: " PORT
    PORT="${PORT:-$DEFAULT_PORT}"
else
    read -r -p "Port (must not already be used by another environment on this machine): " PORT
fi
if [[ -z "$PORT" ]]; then
    echo "ERROR: a port is required."
    exit 1
fi

DEFAULT_DB_NAME="portfolio_tracker_${ENV_NAME}"
read -r -p "Database name [$DEFAULT_DB_NAME]: " DB_NAME
DB_NAME="${DB_NAME:-$DEFAULT_DB_NAME}"

read -r -s -p "PostgreSQL 'casaos' user password (set in scripts/setup_server.sh): " PG_PASSWORD
echo
if [[ -z "$PG_PASSWORD" ]]; then
    echo "ERROR: password cannot be empty."
    exit 1
fi

SECRET_KEY="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/init_env.sh for the '$ENV_NAME' environment.
SECRET_KEY=$SECRET_KEY

# Use 0.0.0.0 when the application must be reachable from a mobile device on the LAN/Tailscale.
HOST=0.0.0.0
LOG_LEVEL=INFO

DATABASE_URL=postgresql://casaos:$PG_PASSWORD@localhost:5432/$DB_NAME
DB_NAME=$DB_NAME

PORT=$PORT
EOF

unset PG_PASSWORD

chmod 600 "$ENV_FILE"

echo
echo "Wrote $ENV_FILE (permissions 600, not committed to git)."
echo
echo "Next:"
echo "  docker exec postgresql createdb -U casaos $DB_NAME"
echo "  ./scripts/init_database.sh"
